### ISSUE TITLE
Add readiness and liveness probes to K8s deployment

### ISSUE THREAD

**Issue by outofcoffee** [gatehill/kamara#1]
Example:

```
        # Only serve traffic when ready
        readinessProbe:
          httpGet:
            path: /system/status
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10

        # Triggers restart on failure
        livenessProbe:
          httpGet:
            path: /system/status
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
```
